### ISSUE TITLE
One-liner Setup for shortfin

### ISSUE THREAD

**Issue by renxida** [nod-ai/shark-ai#246]
There should be a "Quickstart guide" on top of readme.md that lets people pip install shortfin and run a server really quickly, from an environment with no dependencies installed.

**Comment by ScottTodd** [comment]
Fixed as part of https://github.com/nod-ai/shark-ai/issues/458. See https://github.com/nod-ai/shark-ai/blob/main/docs/user_guide.md

**Comment by ScottTodd** [comment]
Oh, fixed for SDXL at least with those pages. Llama now also has https://github.com/nod-ai/shark-ai/blob/main/docs/shortfin/llm/user/e2e_llama8b_mi300x.md, but we'll want to keep iterating on those pages as support for more devices and models is finished.
