### ISSUE TITLE
Shark V1 Nov 2024 Release Testing Bash

### ISSUE THREAD

**Issue by pdhirajkumarprasad** [nod-ai/shark-ai#512]
Please login into a MI300X machine. For AMD Shark Team, see internal slack channel on available machines.

- Create a python virtual environment of your liking and activate it. If you are new to python, the simplest way is to do following the first time:
```
python3.12 -m venv .venv
source .venv/bin/activate
```
and following subsequently:
```
source .venv/bin/activate
```

- Use the instruction on this [Shark V1 Release Testing Bash](https://github.com/nod-ai/SHARK-Platform/tree/main/shortfin/python/shortfin_apps/sd) to install and test the shark V1 release.

Feel free to test it however you like but here are some guidelines you could follow.

## Testing guidelines

- Run multiple servers on the same machine with different port numbers
- Logout and login and try multiple times 
- Try using different options (flags) for servers and clients (see tables below)

Multiple people may try the same feature so whoever is trying a particular feature, please put your under "Testers" column in the tables below.

## shortfin_apps.sd.server with different options:

| Flags | options |Testers|Issues|
|---|---|---|---|
|--host HOST |
|--port PORT |
|--root-path ROOT_PATH |
|--timeout-keep-alive |
|--device | local-task,hip,amdgpu |
|--target | gfx942,gfx1100 | | https://github.com/nod-ai/SHARK-Platform/issues/515
|--device_ids |
|--tokenizers |
|--model_config |
| --workers_per_device | 
| --fibers_per_device |
| --isolation |	per_fiber, per_call, none |
| --show_progress  |
| --trace_execution | 
| --amdgpu_async_allocations |
| --splat   |
| --build_preference | compile,precompiled |
| --compile_flags |
| --flagfile FLAGFILE | | | https://github.com/nod-ai/SHARK-Platform/issues/515
| --artifacts_dir ARTIFACTS_DIR |

## shortfin_apps.sd.simple_client with different options:

| Flags |Testers|Issues|
|---|---|---|
|--file|
|--reps|
|--save|
|--outputdir|
|--steps|
|--interactive|

## other issues
|Issue description | issue no |
|---|---|
|||

**Comment by dan-garvey** [comment]
not a critique, just something I noticed, takes about 12 min for server startup.

**Comment by IanNod** [comment]
I had same server startup time. I attributed it to downloading models/weights on setup. 

Minor critique it does not look like we are changing the random latents generated. Not sure where that is controlled but was seeing the same image generated given the same prompt

**Comment by dan-garvey** [comment]
yeah as Ian said the seed appears fixed, I think when reps>1 it should be changed. 

```            async for i in async_range(args.reps):
                **data["seed"] = [i]**
                pending.append(
                    asyncio.create_task(send_request(session, i, args, data))
                )
                await asyncio.sleep(
                    1
                )  # Wait for 1 second before sending the next request```
                
                maybe this works?

**Comment by dan-garvey** [comment]
well at least in the args.reps>1 case

**Comment by archana-ramalingam** [comment]
At cold start, incomplete model download causes the following issue. Deleting cached models and re-downloading them fixed it. 

> INFO:root:Loading parameter fiber 'model' from: /home/aramalin/.cache/shark/genfiles/sdxl/stable_diffusion_xl_base_1_0_punet_dataset_i8.irpa
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/home/aramalin/SHARK-Platform/3.12.venv/lib/python3.12/site-packages/shortfin_apps/sd/server.py", line 388, in <module>
>     main(
>   File "/home/aramalin/SHARK-Platform/3.12.venv/lib/python3.12/site-packages/shortfin_apps/sd/server.py", line 376, in main
>     sysman = configure(args)
>              ^^^^^^^^^^^^^^^
>   File "/home/aramalin/SHARK-Platform/3.12.venv/lib/python3.12/site-packages/shortfin_apps/sd/server.py", line 115, in configure
>     sm.load_inference_parameters(*datasets, parameter_scope="model", component=key)
>   File "/home/aramalin/SHARK-Platform/3.12.venv/lib/python3.12/site-packages/shortfin_apps/sd/components/service.py", line 116, in load_inference_parameters
>     p.load(path, format=format)
> ValueError: shortfin_iree-src/runtime/src/iree/io/formats/irpa/irpa_parser.c:16: OUT_OF_RANGE; file segment out of range (1766080 to 2614665369 for 2612899290, file_size=726679552); verifying storage segment
>

**Comment by vivekkhandelwal1** [comment]
I have to additionally install the `pip install dataclasses-json Pillow` to get the SDXL Server running.

I'm getting the following error on SDXL client after entering the prompt:
```
Enter a prompt:  Generate a beautiful image of sunrise.Sending request with prompt:  ['Generate a beautiful image of sunrise.']Sending request batch # 0Traceback (most recent call last):  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1013, in _read_ready__data_received    data = self._sock.recv(self.max_size)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ConnectionResetError: [Errno 104] Connection reset by peerThe above exception was the direct cause of the following exception:Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main  File "<frozen runpy>", line 88, in _run_code  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/shortfin_apps/sd/simple_client.py", line 228, in <module>    main(sys.argv)  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/shortfin_apps/sd/simple_client.py", line 222, in main    asyncio.run(interactive(args))  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run    return runner.run(main)           ^^^^^^^^^^^^^^^^  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run    return self._loop.run_until_complete(task)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete    return future.result()           ^^^^^^^^^^^^^^^  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/shortfin_apps/sd/simple_client.py", line 166, in interactive    latency, num_samples = await task                           ^^^^^^^^^^  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/shortfin_apps/sd/simple_client.py", line 63, in send_request    async with session.post(url, json=data) as response:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 1418, in __aenter__    self._resp: _RetType = await self._coro                           ^^^^^^^^^^^^^^^^  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 723, in _request    await resp.start(conn)  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1051, in start    message, payload = await protocol.read()  # type: ignore[union-attr]                       ^^^^^^^^^^^^^^^^^^^^^  File "/home/nod/vivek/.venv/lib/python3.12/site-packages/aiohttp/streams.py", line 667, in read    await self._waiteraiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by pdhirajkumarprasad** [comment]
I have tried almost all flags and different stuff for client/server and added my observation here https://github.com/pdhirajkumarprasad/for_sharing_logs/blob/main/Shark-V1(Nov,%202024)-Bash.md

**Comment by ScottTodd** [comment]
Testing bash complete and v3.0.0 is released. Let's close this?
